name: Deploy Code to Release Branch 🚀
on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:
    name: Push to Release Branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: releases/v4
          folder: .
          clean: false
          single-commit: true
