name: Continuous Integration

on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth:
            0

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.1.0'

      - name: Install Deps
        run: npm install
