# Triggers
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
# Functions
jobs:
  # Build Job
  build:
    # Name of the job
    name: Build
    # The OS to run the job on
    runs-on: ubuntu-latest
    # Steps
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.1.7
      - name: Install node 21
        uses: actions/setup-node@v4.0.3
        with:
          node-version: 21.x
      - name: Install NPM Dependencies
        run: yarn
      - name: Build Project
        run: yarn build
      - name: Upload artifact in order to deploy
        uses: actions/upload-artifact@v4.3.5
        with:
          name: production-files
          path: ./dist

  # Deploy Job
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4.1.8
        with:
          name: production-files
          path: ./dist
      # - name: Deploy to gh pages
      #   uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     github_token: ${{ secrets.GH_ACCESS_TOKEN }}
      #     publish_dir: ./dist
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
