name: Deploy to main
on: push
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3
      - name: Use Node
        uses: actions/setup-node@4
        with:
          node-version: 21
      - name: Install dependencies
        run: yarn

  deploy:
    runs-on: ubuntu-latest
    needs: ["build"]
    steps:
      - uses: actions/checkout@3
      - uses: akjileshns/heroku-deploy@3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "dojo-frontend"
          heroku_email: "vitaliiverdiiev@gmail.com"
